### ISSUE TITLE
DV Web Interface

### ISSUE THREAD

**Issue by pinkdevelops** [jboss-datavirtualization/openshift-cartridge-datavirtualization#33]
I think it would be nice to add in MD how to access the dv-ui out of the box.  Took a little while to figure that part out.

http://<APP-NAME>-<DOMAIN-NAME>.rhcloud.com/dv-ui

user: admin
pass: admin

Thanks

**Comment by mdrillin** [comment]
Good point - added the WebUi access details.
Thanks!
Mark
